export const Team = [
	{
		id: "62050191",
		name: "Punnarat Rattanapawan",
		role: [
			"Project Manager",
			"Head of Back-end Department",
			"Back-end Teacher",
			"Python-GA",
		],
		image: "/images/contributor/Punnarat.jpg",
		isPM: true,
	},
	{
		id: "62050133",
		name: "Kunasin Charusiriwat",
		role: ["GA-Information", "Python-GA"],
		image: "/images/contributor/Kunasin.jpg",
		isPM: false,
	},
	{
		id: "62050134",
		name: "Jatuphol Chailittikun",
		role: ["Head of Meeting Gathering", "GA-Information"],
		image: "/images/contributor/Jatuphol.jpg",
		isPM: false,
	},
	{
		id: "62050146",
		name: "Chutiyakan Oonjon",
		role: ["Front-end", "GA-Information", "Slide Maker"],
		image: "/images/contributor/Chutiyakan.jpg",
		isPM: false,
	},
	{
		id: "62050149",
		name: "Noppawat Boonma",
		role: ["GA-Information", "Python-GA"],
		image: "/images/contributor/Noppawat.jpg",
		isPM: false,
	},
	{
		id: "62050155",
		name: "Natthadecha Kijsamrej",
		role: [
			"Head of Front-end Department",
			"Front-end Teacher",
			"Python-GA",
		],
		image: "/images/contributor/Natthadecha.jpg",
		isPM: false,
	},
	{
		id: "62050163",
		name: "Thirawat Phongsathatkit",
		role: ["Head of UX/UI Design Department", "Front-end", "GA.gif Maker"],
		image: "/images/contributor/Thirawat.jpg",
		isPM: false,
	},
	{
		id: "62050190",
		name: "Praphat Wachiramateekul",
		role: ["Front-end", "GA-Information"],
		image: "/images/contributor/Praphat.jpg",
		isPM: false,
	},
];
